spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jackson:
    date-format: com.microsoft.azure.simpletodo.configuration.RFC3339DateFormat
    serialization: 
      write-dates-as-timestamps: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: <your-Azure-AD-tenant-ID>
        credential:
          client-id: <your-application-ID-of-ToDo>
        app-id-uri: <your-application-ID-URI-of-ToDo>

# The following configuration is for integrating Swagger UI with Azure Active Directory
server:
  tomcat:
    use-relative-redirects: true
  forward-headers-strategy: framework
springdoc:
  swagger-ui:
    use-root-path: true
    oauth:
      use-pkce-with-authorization-code-grant: true
